DROP DATABASE LEMONA_GMP;

CREATE DATABASE LEMONA_GMP;

USE LEMONA_GMP;

CREATE TABLE USER (
    USER_ID VARCHAR(50) PRIMARY KEY,
    PW VARCHAR(255),
    NAME VARCHAR(100),
    DIVISION VARCHAR(100),
    STATUS BOOLEAN DEFAULT TRUE,
    ROLE_ID INT,
    PW_UPDATE_DT DATE,
    CREATE_DT DATE,
    UPDATE_DT DATE
);

CREATE TABLE COMMENT (
    COMMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(1000),
    USER_ID VARCHAR(50)
);

CREATE TABLE ROLE (
    ROLE_ID INT PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50)
);

CREATE TABLE ACCESS (
    ACCESS_ID INT PRIMARY KEY AUTO_INCREMENT,
    ROLE_ID INT NOT NULL,
    PAGE_ID INT NOT NULL
);

CREATE TABLE PAGE (
    PAGE_ID INT PRIMARY KEY AUTO_INCREMENT,
    PAGE_LINK VARCHAR(100),
    MENU_NAME VARCHAR(100),
    PAGE_NAME VARCHAR(100)
);

CREATE TABLE EQUIPMENT_HISTORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	CONTENT VARCHAR(255),
    USER_ID VARCHAR(50),
    COMMENT_ID int,
    CREATE_DT DATETIME
);

CREATE TABLE ALARM_HISTORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	CONTENT VARCHAR(255),
    USER_ID VARCHAR(50),
    COMMENT_ID int,
    CREATE_DT DATETIME
);

CREATE TABLE REPORT_HISTORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	CONTENT VARCHAR(255),
    USER_ID VARCHAR(50),
    COMMENT_ID int,
    CREATE_DT DATETIME
);

CREATE TABLE LOGIN_HISTORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	CONTENT VARCHAR(255),
    USER_ID VARCHAR(50),
    COMMENT_ID int,
    CREATE_DT DATETIME
);

CREATE TABLE USER_HISTORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	CONTENT VARCHAR(255),
    USER_ID VARCHAR(50),
    COMMENT_ID int,
    CREATE_DT DATETIME
);

CREATE TABLE DATA_HISTORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	CONTENT VARCHAR(255),
    USER_ID VARCHAR(50),
    COMMENT_ID int,
    CREATE_DT DATETIME
);

ALTER TABLE USER 
ADD CONSTRAINT FK_USER_ROLE 
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID);

ALTER TABLE COMMENT 
ADD CONSTRAINT FK_COMMENT_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE ACCESS 
ADD CONSTRAINT FK_ACCESS_ROLE 
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID);

ALTER TABLE ACCESS 
ADD CONSTRAINT FK_ACCESS_PAGE 
FOREIGN KEY (PAGE_ID) REFERENCES PAGE(PAGE_ID);

ALTER TABLE EQUIPMENT_HISTORY 
ADD CONSTRAINT FK_EQUIPMENT_HISTORY_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE ALARM_HISTORY
ADD CONSTRAINT FK_ALARM_HISTORY_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE REPORT_HISTORY
ADD CONSTRAINT FK_REPORT_HISTORY_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE LOGIN_HISTORY
ADD CONSTRAINT FK_LOGIN_HISTORY_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE USER_HISTORY
ADD CONSTRAINT FK_USER_HISTORY_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE DATA_HISTORY
ADD CONSTRAINT FK_DATA_HISTORY_USER
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE EQUIPMENT_HISTORY 
ADD CONSTRAINT FK_EQUIPMENT_HISTORY_COMMENT
FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(COMMENT_ID);

ALTER TABLE ALARM_HISTORY
ADD CONSTRAINT FK_ALARM_HISTORY_COMMENT
FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(COMMENT_ID);

ALTER TABLE REPORT_HISTORY
ADD CONSTRAINT FK_REPORT_HISTORY_COMMENT
FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(COMMENT_ID);

ALTER TABLE LOGIN_HISTORY
ADD CONSTRAINT FK_LOGIN_HISTORY_COMMENT
FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(COMMENT_ID);

ALTER TABLE USER_HISTORY
ADD CONSTRAINT FK_USER_HISTORY_COMMENT
FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(COMMENT_ID);

ALTER TABLE DATA_HISTORY
ADD CONSTRAINT FK_DATA_HISTORY_COMMENT
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

INSERT INTO ROLE (ROLE_NAME) VALUES 
('ROOT'),
('ADMIN'), 
('MANAGER'),
('USER');

INSERT INTO PAGE (PAGE_LINK, MENU_NAME, PAGE_NAME) VALUES
('equipment-history', '이력 조회', '설비 가동 이력 조회'),
('alarm-history', '이력 조회', '설비 알람 이력 조회'),
('report-history', '이력 조회', '보고서 생성 이력 조회'),
('login-history', '이력 조회', '접속 이력 조회'),
('user-history', '이력 조회', '사용자 관리 이력 조회'),
('data-history', '이력 조회', '데이터 관리 이력 조회'),
('user-create', '사용자 관리', '사용자 생성'),
('user-update', '사용자 관리', '사용자 수정'),
('access-update', '사용자 관리', '권한별 접근 가능 페이지 관리'),
('password-change', '사용자 관리', '비밀번호 변경'),
('audit-trail', '감사 추적', 'Audit Trail'),
('backup-restore', '데이터 관리', '데이터 백업/복원'),
('plc-test', 'PLC 테스트', 'PLC 통신 테스트');

INSERT INTO ACCESS (ROLE_ID, PAGE_ID) VALUES
('1', '9'),
('1', '13'),
('2', '1'),
('2', '2'),
('2', '3'),
('2', '4'),
('2', '5'),
('2', '6'),
('2', '7'),
('2', '8'),
('2', '9'),
('2', '10'),
('2', '11'),
('2', '12'),
('3', '1'),
('3', '2'),
('3', '3'),
('3', '4'),
('3', '5'),
('3', '6'),
('3', '11'),
('3', '12'),
('4', '1'),
('4', '2'),
('4', '3'),
('4', '4'),
('4', '5'),
('4', '6'),
('4', '11'),
('4', '12');

-- ROOT 사용자 생성 (ROLE_ID: 1)
INSERT INTO USER (USER_ID, PW, NAME, DIVISION, STATUS, ROLE_ID, PW_UPDATE_DT, CREATE_DT, UPDATE_DT)
VALUES (
    'root', 
    '6cbefd8960d511540f34779628ef4e5a55b758d3be5749cd8878a09b348c052b',
    '시스템 관리자', 
    'IT부서', 
    TRUE, 
    1, 
    NULL,
    CURDATE(), 
    CURDATE()
);

-- ADMIN 사용자 생성 (ROLE_ID: 2) 
INSERT INTO USER (USER_ID, PW, NAME, DIVISION, STATUS, ROLE_ID, PW_UPDATE_DT, CREATE_DT, UPDATE_DT)
VALUES (
    'admin01', 
    '6cbefd8960d511540f34779628ef4e5a55b758d3be5749cd8878a09b348c052b',
    '관리자', 
    '관리부', 
    TRUE, 
    2, 
    NULL,
    CURDATE(), 
    CURDATE()
);

-- MANAGER 사용자 생성 (ROLE_ID: 3)
INSERT INTO USER (USER_ID, PW, NAME, DIVISION, STATUS, ROLE_ID, PW_UPDATE_DT, CREATE_DT, UPDATE_DT)
VALUES (
    'manager01', 
    '6cbefd8960d511540f34779628ef4e5a55b758d3be5749cd8878a09b348c052b',
    '매니저', 
    '생산부', 
    TRUE, 
    3, 
    NULL,
    CURDATE(), 
    CURDATE()
);

-- USER 사용자 생성 (ROLE_ID: 4)
INSERT INTO USER (USER_ID, PW, NAME, DIVISION, STATUS, ROLE_ID, PW_UPDATE_DT, CREATE_DT, UPDATE_DT)
VALUES (
    'user01', 
    '6cbefd8960d511540f34779628ef4e5a55b758d3be5749cd8878a09b348c052b',
    '일반사용자', 
    '품질관리부', 
    TRUE, 
    4, 
    NULL,
    CURDATE(), 
    CURDATE()
);

select * from user;